### ISSUE TITLE
Conda Virtual environment name not visible

### ISSUE THREAD

**Issue by ParthBibekar** [andresgongora/synth-shell-prompt#16]
Hi,
Whenever I activate a virtual environment, it doesn't show that the environment has been activated. 
Usually a terminal shows this   `(environment-name) user@ubuntu-budgie:$  `
It would be nice to have something like this in synth-shell as well.

**Comment by andresgongora** [comment]
I guess conda is gaining lots of track - same request as in #15

**Comment by andresgongora** [comment]
Can you guys test whether 937991e works as intended? It should first check for conda environments, then for python environments, and if none, do nothing :)

**Comment by ParthBibekar** [comment]
Yes it works completely fine for me. Thanks a lot!

**Comment by andresgongora** [comment]
@ParthBibekar Ok! I'll close this issue then for now. If any issue comes up, feel free to reopen it ;)
