### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by AmbyrElan** [andresgongora/synth-shell-prompt#19]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I installed synth-shell and expected it the configuration to take effect.  The installation didn't make any changes to my bash shell. 

**Screenshots**
![image](https://user-images.githubusercontent.com/89077791/139106486-9f078c4b-d177-489b-ad68-e7401dfbaa55.png)

**Additional context**
I followed this video tutorial : [Fancy Bash Prompt! Customize Linux Terminal with Synth-Shell](https://www.youtube.com/watch?v=jS-QZKjAd-U)

I use iTerm2 on Mac

**Comment by andresgongora** [comment]
This seems to be the solution: https://superuser.com/questions/320065/bashrc-not-sourced-in-iterm-mac-os-x (likely)

**Comment by AmbyrElan** [comment]
Hi Andres,

This article was super helpful! In Iterm2 Prefernces -> Profiles adding `source ~/.bashrc` to the Command : Send text at start field got the terminal theme to load on start up.

Thank you so much for your help!

**Comment by andresgongora** [comment]
Awesome! I'm closing this issue then :D
