### ISSUE TITLE
Branch dirty - square character

### ISSUE THREAD

**Issue by Geek-Cat666** [andresgongora/synth-shell-prompt#21]
I'm not sure but I think that branch dirty is being wrongly rendered (square character after branch name)
![image](https://user-images.githubusercontent.com/95128480/145020974-d53bf030-f512-4154-bb0b-28c49d7d230b.png)

**Comment by andresgongora** [comment]
It's actually correct. But feel free to go to the config file `~/.config/synth-shell/synth-shell-prompt.config` and change it to any other character you like. The variable you have to edit is `git_symbol_dirty=' □'` :)

If you find a character that looks better, kindly let me know and I'll update the default config

**Comment by andresgongora** [comment]
I've just updated the default characters. They should be way less confusing now. Feel free to reopen this issue if you run into anything weird :)
