### ISSUE TITLE
Weird rectangles around prompt in Ubuntu terminal

### ISSUE THREAD

**Issue by GreatUsername63** [andresgongora/synth-shell-prompt#23]
**Describe the bug**
Weird colored rectangles stand out around the synth shell prompt. Its most noticeable around the path (white one with ~). Changing font, font size or spacing does not solve the bug.

**To Reproduce**
1. Get Ubuntu
2. Install synth shell with the special prompt
3. See error

**Expected behavior**
For the rectangles to not appear and the prompt looking clean like so: https://ibb.co/4ZZpQTT

**Screenshots**
With default Ubuntu font and size: https://ibb.co/ZSGmMYg
With alternate font and size: https://ibb.co/y6GqNfQ

**Additional context**
YouTube video i used to customize the terminal (dude had the same thing but didn't explain how to solve it): https://youtu.be/jS-QZKjAd-U
Reddit thread of me asking about this: https://www.reddit.com/r/linuxquestions/comments/rjrslp/synth_shell_fancy_bash_prompt_shows_some_slightly/?utm_source=share&utm_medium=web2x&context=3

**Comment by andresgongora** [comment]
I'm glad you managed to get it to look crisp. Sorry it didn't work with the font you wanted. I'm closing this issue for now. Feel free to reopen it if you experience other related problems. Otherwise, enjoy :)
