### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by Resist-1** [andresgongora/synth-shell-prompt#25]
/**.config/synth-shell/synth-shell-prompt.sh**:type:563: bad option: -t

I get this error after installing **synth-shell-prompt** only when I re-launch the terminal again.
But after typing **clear** I get:

_zsh_autosuggest_bind_widget:13: invalid subscript

on top of the terminal every time. 

**Also Terminal has no effect at all.**

**Comment by andresgongora** [comment]
I fear zsh is not fully suppoerted. Can you check what line 563 in `/.config/synth-shell/synth-shell-prompt.sh` reads? Maybe it's a single command that is failing :)

**Comment by Xm24mX** [comment]
Im having the same problem, how do you fix it?

**Comment by andresgongora** [comment]
I fear zsh is not supported yet since none of the developers use it. But you are welcome to contribute to synth-shell if you find the time to fix the bugs that affect it :)
