### ISSUE TITLE
Clock on Synth Shell

### ISSUE THREAD

**Issue by sansroot** [andresgongora/synth-shell-prompt#30]
Is it possible to enable the clock on Synth Shell?
Sorry for bothering with basic questions, but i couldn't find any way to enable it!

Thank you in advance!

**Comment by andresgongora** [comment]
Yes and no. It's should be fairly easy to add a clock. However, keep in
mind that said clock will no update as time passes, it will show the clock
time of when the prompt was drawn. So it might not be super useful

**Comment by andresgongora** [comment]
I was implementing the clock you suggested when I noticed I had already done so. You can enable the clock by going to your prompt config file and changing the line `format="USER HOST PWD CLOCK"` to include your clock. You should also be able to find the appropriate color config params in said file. 

Also, I've made it possible to change the format of the clock (it's really a call to `date` under the hood) but that's still in the development branch. Feel free to experiment with it if you like ;)
