### ISSUE TITLE
How can I change the length of current working path

### ISSUE THREAD

**Issue by tNhanDerivative** [andresgongora/synth-shell-prompt#31]
How can I change the length of current working directory. Default value is too short
If it's too complicated can I just turn off shorten path

**Comment by andresgongora** [comment]
You can edit the config under `~/.config/synth-shell`. Just set it to whatever value you like. I'ts all documented there ;) Feel free to reopen this issue if it doesn't work for you

**Comment by tNhanDerivative** [comment]
I have already tried that. 
In file `synth-shell-prompt.sh` in the function `shortenPath()`  there's a `max_length` variable I've already change that, it does nothing.
I even comment out all code inside `shortenPath()`, nothing change.

**Comment by andresgongora** [comment]
Ohh that's quite odd. Are you running synth-shell prompt for your normal user or for root? Also, after reinstalling, does a new config file appear next to the old one? What OS are you on? What's your terminal emulator?

**Comment by tNhanDerivative** [comment]
I'm using Fedora 38, my normal user. Okey I will reinstall it and see what happen
