### ISSUE TITLE
Strange characters in propmt

### ISSUE THREAD

**Issue by archenroot** [andresgongora/synth-shell-prompt#34]
I just installed your solution under WSL2 Ubuntu and getting weird graphical results:
When command prompt started from wsl2 xfce4-terminal package via display variable 
**
![image](https://github.com/andresgongora/synth-shell-prompt/assets/553512/87019844-42b5-4aa2-b6b6-ff3aba0477e2)
**
When xfce4-terminal started within XRDP session:
![image](https://github.com/andresgongora/synth-shell-prompt/assets/553512/0ace77bb-9669-4b1d-8b5a-d5c72598af6d)
When accessing WSL ubuntu via Windows PowerShell:
![image](https://github.com/andresgongora/synth-shell-prompt/assets/553512/2e156dbe-4abd-42c5-bca9-ab50c09cb81e)

Any idea how to fix this?

**Comment by andresgongora** [comment]
Hi, ha e you installed Powerline fonts as described in the setup guide?

**Comment by archenroot** [comment]
I didn't, I was following this guide: https://www.linuxfordevices.com/tutorials/linux/beautify-bash-shell

I will double check docs here in github and let you know

**Comment by archenroot** [comment]
Ok, I installed:
` sudo apt install fonts-powerline`

still the result is same, I also rebooted WSL instance, no change

**Comment by archenroot** [comment]
thx for suggestion

**Comment by archenroot** [comment]
I am reopening this issue as I would like to fix the the Windows WSL Powershell display, at moment it looks like this still broken:
![image](https://github.com/andresgongora/synth-shell-prompt/assets/553512/dd5a0bfe-ffa4-4b20-b497-0d0d72ec5b97)
Would you be so kind and tell me which exact font is being used as default from powerline/fonts? I downloaded full package, but due to corporate policy I cannot run full install script (its blocked by policy), but if you tell me the exact name of the font i can install it manually as such operation is allowed on my laptop. Thanks a lot for help

**Comment by archenroot** [comment]
ok, so it seems its an issue with Font which is being used for the powershell console, the list of fonts which can be used is quite small and each displays prompt differently:
![image](https://github.com/andresgongora/synth-shell-prompt/assets/553512/f95cbf79-3759-4665-a95c-d23d07afdd44)

This font seems better, but still not showing "arrow" character:
![image](https://github.com/andresgongora/synth-shell-prompt/assets/553512/7a199961-82bd-423a-ba9a-030b62674968)

**Comment by archenroot** [comment]
Ok, it seems powershell framework is kind of limited or I don't know what to hack in windows registry, but I tried now alternative terminal emulator for windows called ConEmu and it works well:
![image](https://github.com/andresgongora/synth-shell-prompt/assets/553512/2609c24b-edec-4535-be52-8c4e13be6ea0)

So it seems it is not easy for powershell terminal to access all fonts on machine.
