### ISSUE TITLE
Prompt very slow when entering a directory with a git repo

### ISSUE THREAD

**Issue by bb2k** [andresgongora/synth-shell-prompt#36]
On a debian 12 server, when entering some directories with git repos, synth-shell-prompt becomes very slow and type a command is very slow. Only ctrl-c command return to a normal state.
After the ctrl-c i can return to this repo and it's ok

Any way to debug this ?

thx

**Comment by andresgongora** [comment]
Hi. Does the problem persist?

- Maybe you can disable everything related to git to try to isolate the issue. Go to the config file, find the related section, and turn the options off.
- To answer your question, when you enter a git directory, the script runs the following:
    - https://github.com/andresgongora/synth-shell-prompt/blob/98c046491d16623a84f47673a07a70f81b1a272a/synth-shell-prompt/synth-shell-prompt.sh#L76

Let me know if you make any progress ;)

**Comment by bb2k** [comment]
OK I fixed it by changing 
`git_update_period_minutes=15`
to
`git_update_period_minutes=-1`
in` ~/.config/synth-shel/synth-shell-prompt.config`
