### ISSUE TITLE
Optional spacing in prompt

### ISSUE THREAD

**Issue by periode** [andresgongora/synth-shell-prompt#4]
Hi,

I changed the formatting of the prompt in `fancy-bash-prompt.config` and I was wondering if it was possible to make the whitespace that's pads the user, host, pwd and branch. Would it make sense to make it optional, by adding a field in the config file? These are the spaces I'm talking about (example in which the separator character is already a whitespace):

![spacing](https://user-images.githubusercontent.com/1785254/80353866-472ef680-8876-11ea-98f4-b569d9cd0fb8.png)

Not sure how much of a specific case it is, but it could at least be nice to left align the prompt with the rest of other commands (`cat`, etc.), and it works with brighter background colors, but not so much with darker ones, imo.

Happy to take care of it, but I'm still trying to figure out where it is set in `fancy-bash-prompt.sh`? Or would it make sense to work on this directly in [synth-shell-prompt](https://github.com/andresgongora/synth-shell-prompt)?

**Comment by periode** [comment]
Hi @andresgongora,

Thanks for the quick reply!

Yep, I did try the `\t` separator, but what I'm trying to achieve is this:
```${user}${separator}${host}${separator}${pwd}${separator}${git}${separator}```

but the current behaviour as I understand and see it now is:
```${user}${extrawhitespace}${separator}${extrawhitespace}${host}${extrawhitespace}${separator}${extrawhitespace}${pwd}${extrawhitespace}${separator}${extrawhitespace}${git}${extrawhitespace}${separator}```

What happens now is, with `separator_char=' '` (single whitespace), the effective result is that there are two whitespaces surrounding the separator_char and there's a whitespace preceding the `${user}`.

and I'm not certain where those additional whitespaces come from (through color formatting?)

As for the colors, it's not an issue at all (it works great!), but rather an illustration of why I think making those extra whitespaces optional would be a nice addition!

**Comment by andresgongora** [comment]
I just pushed 405841f to `develop`. Everything should now be configurable :)
I've added a new line to the config file, `segment_padding=' '`. Try the following:
```
separator_char='' # no separator
segment_padding='\t' #tab
```
Let's see if that work. If so, we'll continue playing around and separating the first padding (in fron of the user) from the rest until we attain the desired result.

**Comment by andresgongora** [comment]
I just went all in. Please check the new config file in `develop` after commit f099735. YOu should be able to configure all sort of padding combinations right now. I suggest:
```
separator_char=''
separator_padding_left='\t'
separator_padding_right='\t'
prompt_horizontal_padding=''
prompt_final_padding=''
segment_padding=''
```
Let me know if you can achieve the desired result with that. Also try to play around with all the other parameters. I think there should be at least one combination that gives you the desired result :)

**Comment by periode** [comment]
Yep, it works perfectly, thanks a lot!

Unrelated note: the setup section in the README is about installing synth-shell-greeter, and not-synth-shell-prompt (and the overview section mentions `fancy-bash-prompt.sh` instead of `synth-shell-prompt.sh`.

Thanks :)

**Comment by andresgongora** [comment]
Perfect! I've fixed the readme as well. Please stay for now on the develop branch. I don't have the time to merge into master atm. let me know if any other bug arises :)

**Comment by periode** [comment]
I will, thanks!
